 create database internship;
 DROP TABLE EMPLOYEE;
create table EMPLOYEE(
ID INT PRIMARY KEY , DEPARTMENT VARCHAR(10) ,SALARY DOUBLE,EMPLOYEENAME VARCHAR(50)) ;
INSERT INTO EMPLOYEE VALUES(2,'HR',56000.0,'RADHA');
INSERT INTO EMPLOYEE VALUES(3,'INTERN',90000.0,'KRISHAN');
INSERT INTO EMPLOYEE VALUES(4,'HR',90000.0,'HARI')
,(5,'CEO',6000.0,'SUNDAR')
,(6,'PM',9000.0,'VIJAY'),(7,'PMO',10000.0,'ROHAN');
SELECT *FROM EMPLOYEE WHERE SALARY ='9000.0';
SET SQL_SAFE_UPDATES = 0;
 UPDATE EMPLOYEE SET SALARY=800000.0 WHERE DEPARTMENT='HR';
 DELETE FROM EMPLOYEE WHERE SALARY = 9000.0;
 SELECT *FROM EMPLOYEE WHERE SALARY=80000.0 AND SALARY =90000.0;
 SELECT *FROM EMPLOYEE WHERE SALARY <7000.0 OR 10000.0 ORDER BY SALARY ASC LIMIT 2;

ALTER TABLE EMPLOYEE DROP COLUMN DEPARTMENT;
SELECT * FROM EMPLOYEE;
ALTER TABLE EMPLOYEE RENAME  COLUMN EMPLOYEENAME TO  EMPLOYEE_NAME;
ALTER TABLE EMPLOYEE ADD EMP_ID VARCHAR(50);

 RENAME TABLE EMPLOYEE TO EMP;
 ALTER TABLE EMP
ADD EMAIL VARCHAR(50);
 
