DROP DATABASE COMPANY ;
CREATE DATABASE COMPANY;
USE COMPANY;


CREATE TABLE EMP(
    EMP_ID INT PRIMARY KEY,
    JOININGDATE DATE,
    SALARY DOUBLE
);

INSERT INTO EMP VALUES
(101,'2024-12-20',50000.0),
(102,'2024-12-21',59000.0),
(103,'2024-12-22',59900.0),
(104,'2024-12-25',50990.0);

ALTER TABLE EMP ADD COLUMN EMAIL VARCHAR(50);
ALTER TABLE EMP ADD COLUMN UserId INT;

 ALTER TABLE EMP ADD COLUMN    DEPT_ID INT;

UPDATE EMP SET EMP_ID=106 WHERE EMP_ID=102;

UPDATE EMP SET EMAIL='Radhakrishan81217@gmail.com' WHERE EMP_ID=101;
-- UPDATE EMP SET DEPT_ID = 101  WHERE EMP_ID=101;
UPDATE EMP SET EMAIL='krishan81217@gmail.com' WHERE EMP_ID=106;
UPDATE EMP SET EMAIL='Radha81217@gmail.com' WHERE EMP_ID=103;
UPDATE EMP SET EMAIL='Radhakrishan18217@gmail.com' WHERE EMP_ID=104;
SELECT *FROM EMP;


CREATE TABLE DEPT(
    DEPT_ID INT ,
    DEPT_NAME VARCHAR(50)
);

-- LTER TABLE EMP ADD COLUMN DEPT_ID INT;
INSERT INTO DEPT VALUES
(101,'HR'),
(103,'PMO'),
(104,'CEO'),(106,'INTERN')
;

SET SQL_SAFE_UPDATES=0;

-- UPDATE DEPT
-- SET DEPT_ID=103
-- WHERE DEPT_NAME='PMO';

ALTER TABLE DEPT ADD COLUMN JOININGDATE DATE;
ALTER TABLE DEPT ADD COLUMN CABIN_NO INT;
ALTER TABLE DEPT
DROP COLUMN CABIN_NO;
ALTER TABLE DEPT ADD COLUMN CABIN_NO INT;
SELECT *FROM DEPT;



UPDATE DEPT SET CABIN_NO=1 WHERE DEPT_ID=101;
UPDATE DEPT SET CABIN_NO=2 WHERE DEPT_ID=103;
UPDATE DEPT SET CABIN_NO=3 WHERE DEPT_ID=104;

;
drop table USER;

CREATE TABLE USER(
    UserId INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100) UNIQUE,
    PHONE VARCHAR(15),
    AGE INT,
    EDUCATION VARCHAR(100),
    USER_NATION VARCHAR(50)
   --  DEPT_ID INT
    
);

INSERT INTO USER
(UserId,FIRST_NAME,LAST_NAME,EMAIL,PHONE,AGE,EDUCATION)
VALUES
(168,'Radha','Yadav','radha@example1.com','9876543210',18,'B.Tech'),
(169,'Krishan','Sharma','krishan@example2.com','9876543211',20,'BCA');
-- UPDATE USER SET DEPT_ID =101 WHERE UserId=168;
-- UPDATE USER SET DEPT_ID =103 WHERE UserId=169;



ALTER TABLE USER
ADD CONSTRAINT fk_user_dept
FOREIGN KEY(DEPT_ID)
REFERENCES DEPT(DEPT_ID);


-- UPDATE EMP TABLE

UPDATE EMP SET UserId=168, DEPT_ID=155 WHERE EMP_ID=101;
UPDATE EMP SET UserId=169, DEPT_ID=152 WHERE EMP_ID=106;
UPDATE EMP SET DEPT_ID=152 WHERE EMP_ID=103;
UPDATE EMP SET DEPT_ID=152 WHERE EMP_ID=104;
SELECT *FROM EMP;

ALTER TABLE EMP
ADD CONSTRAINT fk_emp_user
FOREIGN KEY(UserId)
REFERENCES USER(UserId);

ALTER TABLE EMP
ADD CONSTRAINT fk_emp_dept
FOREIGN KEY(DEPT_ID)
REFERENCES DEPT(DEPT_ID);

SELECT * FROM EMP;
SELECT * FROM USER;
SELECT * FROM DEPT;


SELECT DISTINCT EDUCATION
FROM USER;

SELECT DISTINCT DEPT_ID
FROM USER;


SELECT *
FROM USER
ORDER BY AGE ASC;

SELECT *
FROM EMP
ORDER BY SALARY DESC;

SELECT *
FROM DEPT
ORDER BY DEPT_NAME ASC;


SELECT EDUCATION, COUNT(*) AS TOTAL_USERS
FROM USER
GROUP BY EDUCATION;

SELECT DEPT_ID, COUNT(*) AS TOTAL_USERS
FROM USER
GROUP BY DEPT_ID;

SELECT DEPT_ID, AVG(AGE) AS AVG_AGE
FROM USER
GROUP BY DEPT_ID;

SELECT EDUCATION, COUNT(*) AS TOTAL_USERS
FROM USER
GROUP BY EDUCATION
HAVING EDUCATION='BCA';


-- INNER JOIN

SELECT *
FROM EMP E
INNER JOIN USER U
ON E.UserId = U.UserId;


-- LEFT JOIN

SELECT *
FROM EMP E
LEFT JOIN USER U
ON E.UserId = U.UserId;


-- RIGHT JOIN
SELECT *
FROM EMP E
RIGHT JOIN USER U
ON E.UserId = U.UserId;

-- FULL OUTER JOIN 

SELECT *
FROM EMP E
LEFT JOIN USER U
ON E.UserId = U.UserId
 UNION
 SELECT *
FROM EMP E
RIGHT JOIN USER U
ON E.UserId = U.UserId;
































































































-- CREATE DATABASE COMPANY;
-- USE COMPANY;

-- -- ==========================
-- -- CREATE EMP TABLE
-- -- ==========================
-- CREATE TABLE EMP(
--     EMP_ID INT PRIMARY KEY,
--     JOININGDATE DATE,
--     SALARY DOUBLE
-- );

-- INSERT INTO EMP VALUES
-- (101,'2024-12-20',50000.0),
-- (102,'2024-12-21',59000.0),
-- (103,'2024-12-22',59900.0),
-- (104,'2024-12-25',50990.0);

-- ALTER TABLE EMP ADD COLUMN EMAIL VARCHAR(50);
-- ALTER TABLE EMP ADD COLUMN UserId INT;
--  ALTER TABLE EMP ADD COLUMN DEPT_ID INT;

-- UPDATE EMP SET EMP_ID=106 WHERE EMP_ID=102;

-- UPDATE EMP SET EMAIL='Radhakrishan81217@gmail.com' WHERE EMP_ID=101;
-- UPDATE EMP SET EMAIL='krishan81217@gmail.com' WHERE EMP_ID=106;
-- UPDATE EMP SET EMAIL='Radha81217@gmail.com' WHERE EMP_ID=103;
-- UPDATE EMP SET EMAIL='Radhakrishan18217@gmail.com' WHERE EMP_ID=104;

-- -- ==========================
-- -- CREATE DEPT TABLE
-- -- ==========================
-- CREATE TABLE DEPT(
--     DEPT_ID INT PRIMARY KEY,
--     DEPT_NAME VARCHAR(50)
-- );

-- ALTER TABLE EMP ADD COLUMN DEPT_ID INT;
-- INSERT INTO DEPT VALUES
-- (101,'HR'),
-- (103,'PMO'),
-- (104,'CEO'),(106,'INTERN')
-- ;

-- SET SQL_SAFE_UPDATES=0;

-- UPDATE DEPT
-- SET DEPT_ID=101
-- WHERE DEPT_NAME='PMO';

-- ALTER TABLE DEPT ADD COLUMN JOININGDATE DATE;
-- ALTER TABLE DEPT ADD COLUMN CABIN_NO INT;
-- ALTER TABLE DEPT
-- DROP COLUMN CABIN_NO;
-- ALTER TABLE DEPT ADD COLUMN CABIN_NO INT;
-- SELECT *FROM DEPT;



-- UPDATE DEPT SET CABIN_NO=1 WHERE DEPT_ID=152;
-- UPDATE DEPT SET CABIN_NO=2 WHERE DEPT_ID=155;
-- UPDATE DEPT SET CABIN_NO=3 WHERE DEPT_ID=154;

-- DELETE FROM DEPT
-- WHERE DEPT_ID=154;

-- -- ==========================
-- -- CREATE USER TABLE
-- -- ==========================
-- CREATE TABLE USER(
--     UserId INT PRIMARY KEY AUTO_INCREMENT,
--     FIRST_NAME VARCHAR(50),
--     LAST_NAME VARCHAR(50),
--     EMAIL VARCHAR(100) UNIQUE,
--     PHONE VARCHAR(15),
--     AGE INT,
--     EDUCATION VARCHAR(100),
--     USER_NATION VARCHAR(50),
--     DEPT_ID INT
-- );

-- INSERT INTO USER
-- (UserId,FIRST_NAME,LAST_NAME,EMAIL,PHONE,AGE,EDUCATION,DEPT_ID)
-- VALUES
-- (168,'Radha','Yadav','radha@example1.com','9876543210',18,'B.Tech',155),
-- (169,'Krishan','Sharma','krishan@example2.com','9876543211',20,'BCA',152);

-- -- ==========================
-- -- FOREIGN KEY USER -> DEPT
-- -- ==========================
-- ALTER TABLE USER
-- ADD CONSTRAINT fk_user_dept
-- FOREIGN KEY(DEPT_ID)
-- REFERENCES DEPT(DEPT_ID);

-- -- ==========================
-- -- UPDATE EMP TABLE
-- -- ==========================
-- UPDATE EMP SET UserId=168, DEPT_ID=155 WHERE EMP_ID=101;
-- UPDATE EMP SET UserId=169, DEPT_ID=152 WHERE EMP_ID=106;
-- UPDATE EMP SET DEPT_ID=152 WHERE EMP_ID=103;
-- UPDATE EMP SET DEPT_ID=152 WHERE EMP_ID=104;
-- SELECT *FROM EMP;
-- -- ==========================
-- -- FOREIGN KEYS EMP
-- -- ==========================
-- ALTER TABLE EMP
-- ADD CONSTRAINT fk_emp_user
-- FOREIGN KEY(UserId)
-- REFERENCES USER(UserId);

-- ALTER TABLE EMP
-- ADD CONSTRAINT fk_emp_dept
-- FOREIGN KEY(DEPT_ID)
-- REFERENCES DEPT(DEPT_ID);

-- -- ==========================
-- -- DISPLAY TABLES
-- -- ==========================
-- SELECT * FROM EMP;
-- SELECT * FROM USER;
-- SELECT * FROM DEPT;

-- -- ==========================
-- -- DISTINCT
-- -- ==========================
-- SELECT DISTINCT EDUCATION
-- FROM USER;

-- SELECT DISTINCT DEPT_ID
-- FROM USER;

-- -- ==========================
-- -- ORDER BY
-- -- ==========================
-- SELECT *
-- FROM USER
-- ORDER BY AGE ASC;

-- SELECT *
-- FROM EMP
-- ORDER BY SALARY DESC;

-- SELECT *
-- FROM DEPT
-- ORDER BY DEPT_NAME ASC;

-- -- ==========================
-- -- GROUP BY
-- -- ==========================
-- SELECT EDUCATION, COUNT(*) AS TOTAL_USERS
-- FROM USER
-- GROUP BY EDUCATION;

-- SELECT DEPT_ID, COUNT(*) AS TOTAL_USERS
-- FROM USER
-- GROUP BY DEPT_ID;

-- SELECT DEPT_ID, AVG(AGE) AS AVG_AGE
-- FROM USER
-- GROUP BY DEPT_ID;

-- SELECT EDUCATION, COUNT(*) AS TOTAL_USERS
-- FROM USER
-- GROUP BY EDUCATION
-- HAVING EDUCATION='BCA';

-- -- ==========================
-- -- INNER JOIN
-- -- ==========================
-- SELECT *
-- FROM EMP E
-- INNER JOIN USER U
-- ON E.UserId = U.UserId;

-- -- ==========================
-- -- LEFT JOIN
-- -- ==========================
-- SELECT *
-- FROM EMP E
-- LEFT JOIN USER U
-- ON E.UserId = U.UserId;

-- -- ==========================
-- -- RIGHT JOIN
-- -- ==========================
-- SELECT *
-- FROM EMP E
-- RIGHT JOIN USER U
-- ON E.UserId = U.UserId;

-- -- ==========================
-- -- FULL OUTER JOIN (MySQL)
-- -- ==========================
-- SELECT *
-- FROM EMP E
-- LEFT JOIN USER U
-- ON E.UserId = U.UserId

-- UNION

-- SELECT *
-- FROM EMP E
-- RIGHT JOIN USER U
-- ON E.UserId = U.UserId;